name: vt
channels:
- free
- defaults
- conda-forge
dependencies:
- pip
- sip
- tk
- zlib
- pygments
- pyface
- traitsui
- apptools
- mayavi
- yaml
- freetype
- configobj
- vtk
- six
- sqlite
- numpy
- pyqt
- setuptools
- openssl
- qt
- traits
- pyyaml
- libpng
- envisage
- python #=3.8
- python.app
- readline
- wheel
- pip:
  - cycler
  - matplotlib
  - nibabel
  - pyparsing
  - python-dateutil
  - pytz
  #- mkl
  - scipy