name: vt
channels:
- free
- defaults
- conda-forge
dependencies:
- apptools=4.4.0
- configobj=5.0.6
- envisage=4.5.1
- freetype=2.5.5
- libgfortran=3
- libpng=1.6.22
- mayavi=4.5.0
- mkl=11.3.3
- numpy=1.11.2
- openssl=1.0.2j
- pip=9.0.1
- pyface=5.1.0
- pygments=2.1.3
- pyqt=4.11.4
- python=2.7.13
- pyyaml=3.12
- qt=4.8.7
- readline=6.2
- scipy=0.18.1
- setuptools=27.2.0
- sip=4.18
- six=1.10.0
- sqlite=3.13.0
- tk=8.5.18
- traits=4.6.0
- traitsui=5.1.0
- vtk=6.3.0
- wheel=0.29.0
- yaml=0.1.6
- zlib=1.2.8
